# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{largentinas}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Oldani Pablo"]
  s.date = %q{2010-12-20}
  s.description = %q{mvc de las localidades departamento y provincias de la Argentina (migraciones con todas).}
  s.email = %q{magicche@hotmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/departamentos_controller.rb",
    "app/controllers/localidads_controller.rb",
    "app/controllers/provincias_controller.rb",
    "app/helpers/localidads_helper.rb",
    "app/models/departamento.rb",
    "app/models/localidad.rb",
    "app/models/provincia.rb",
    "app/views/departamentos/_form.html.erb",
    "app/views/departamentos/edit.html.erb",
    "app/views/departamentos/index.html.erb",
    "app/views/departamentos/new.html.erb",
    "app/views/departamentos/show.html.erb",
    "app/views/localidads/_form.html.erb",
    "app/views/localidads/edit.html.erb",
    "app/views/localidads/index.html.erb",
    "app/views/localidads/index.xml.builder",
    "app/views/localidads/new.html.erb",
    "app/views/localidads/show.html.erb",
    "app/views/provincias/_form.html.erb",
    "app/views/provincias/edit.html.erb",
    "app/views/provincias/index.html.erb",
    "app/views/provincias/new.html.erb",
    "app/views/provincias/show.html.erb",
    "config/routes.rb",
    "lib/generators/largentinas/largentinas_generator.rb",
    "lib/generators/largentinas/templates/db/migrate/create_departamentos.rb",
    "lib/generators/largentinas/templates/db/migrate/create_localidads.rb",
    "lib/generators/largentinas/templates/db/migrate/create_provincias.rb",
    "lib/generators/largentinas/templates/db/migrate/departamento_data.rb",
    "lib/generators/largentinas/templates/db/migrate/localidad_data.rb",
    "lib/generators/largentinas/templates/db/migrate/provincia_data.rb",
    "lib/largentinas.rb",
    "test/helper.rb",
    "test/test_largentinas.rb"
  ]
  s.homepage = %q{http://github.com/olvap/largentinas}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{todavia no se que es summary}
  s.test_files = [
    "test/helper.rb",
    "test/test_largentinas.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

